version: "3"
services:
    aghpb_api:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8000
        ports:
            - 8000:8000
        volumes:
            - data:/app/data

volumes:
    data: