[project]
name = "aghpb_api"
description = "Rewrite of anime girls holding programming books api."
authors = [
    {name = "Goldy", email = "goldy@devgoldy.xyz"},
]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
license = { file = "LICENSE" }
dependencies = [
    "requests",
    "importlib-metadata; python_version<'3.8'",
    "fastapi[all]",
    "devgoldyutils",
    "typing-extensions",
    "uvicorn[standard]"
]

dynamic = ["version"]

[project.urls]
GitHub = "https://github.com/THEGOLDENPRO/aghpb_api_rw"
BugTracker = "https://github.com/THEGOLDENPRO/aghpb_api_rw/issues"

[tool.setuptools.dynamic]
version = { attr = "main.__version__" }