name: ty type check

on:
  push:
  pull_request:

jobs:
  ty_type_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install ty
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install .[dev]

      - name: Run ty check
        run: |
          source .venv/bin/activate
          python -m ty check --output-format=github .